services:
  llm-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-fe
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:9000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    # Remove network_mode: "host" to use default bridge
    user: "0:0"